version: '3.9'

services:
  web:
    build: .
    container_name: django-app
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - celery

  redis:
    image: redis:7
    container_name: redis-broker
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery-worker
    command: celery -A myproject worker --loglevel=info
    volumes:
      - .:/code
    environment:
      - DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
