# Generated by Django 5.2.3 on 2025-06-29 03:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productresult',
            options={'ordering': ['price']},
        ),
        migrations.AddField(
            model_name='productresult',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productsearch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productsearch',
            name='last_checked',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productsearch',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productresult',
            name='site',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productresult',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productresult',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productsearch',
            name='target_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
